---
- name: Install metric beat
  hosts: webservers
  become: true
  tasks:
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install metricbeat
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/Metricbeat-config-file.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure docker module for metric beat
    command: sudo metricbeat modules enable docker

  - name: setup metric beat
    command: sudo metricbeat setup

  - name: start metric beat
    command: sudo service metricbeat start

  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes 